travis:
  secure:
    BINSTAR_TOKEN: WRtrPhewuTHpXo1jkbadUOG8Qqimx+8hMrdmsqh6JROOTLXdZT4FbL9GEtX/2arhZHb2KdEQfy0OzitT7hlZagXvuJ+0s5fp9HlAh7JvyNh+QdB/mJOfZP6kEeTuYTv4NW0i3pLiJXrZ4H0hNbmrsXKXJACM49QtBvcy4iDLC77AKfMausmLg1ZrrmQ7/Ohm8vC+Drj9fs8AJJ6BO8SCVmRQe43ft/T/5/JkCjce7xnZbMqGfWlhSDfcbnzoeq2T9F/zAfVqqZHVU/fBL25C1ZjKQ2LxTV/OOk6sxdEhhvrrxhSr8h9euTQKwOq/uQZR9kSio336Y/Rqs0w/z7D+B6rZ/br79mACtuxqysx+meYrcrNhr/9RVx87MJhqND3a8DEv6Jl6rg2Ak4MpRpnD4AWmyVeD0R7hP35n25OSrJhbyRiGTQH9mM12F8Ge2rYoL6f0mUFTjy4QDEfEXLflMEnm4uaobhO3eJSEPgFBfMNi6pfcpXlBGJqAH/f6SerHn+hRNAVdB0xw934obe0UiHgPFVIGbd1879Osu9/hQOX37Ssv3mJH4k3QukRY10XiYWspucTlIcoYGCW1FCy7fp4V8qcPQ5R7cm61A75weNRkZUltOIIDU47hOTY1yKUNVc6e77cSYRLHIY1yNhninnLxcTYT5ZzOd0Ca4lBKq+M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
